### ISSUE TITLE
Remove Except mode for blast

### ISSUE THREAD

**Issue by bartbutler** [ProtonMail/Admin#1]
Just have 'Blast to List' and 'Blast to All Except List'

**Comment by N4M3Z** [comment]
What is the current position w.r.t. to the blasts? Both modes are currently supported by the refactored admin panel.

**Comment by bartbutler** [comment]
That needs to get totally redone and has been disabled API-side for a year or more.

**Comment by N4M3Z** [comment]
Should I remove the except mode from the admin panel then?

**Comment by bartbutler** [comment]
I'm not certain what that is these days, but yes, probably. Also, please ensure that blast doesn't work--for now--attempting to blast should yield an error.

**Comment by N4M3Z** [comment]
Blasting currently works, I will break it then and also hide it from the admin panel.
