### ISSUE TITLE
The admin panel stops searching occasionally

### ISSUE THREAD

**Issue by violetakochoska** [ProtonMail/Admin#28]
Sometimes when I am searching for a user, then click on the lookup organization button, the admin panel will stop working. The buttons become unclickable and you need to refresh the page to continue using it.

Here is a video: http://recordit.co/JCD4c6UJ1A

**Comment by N4M3Z** [comment]
If possible, please provide any other information regarding this issue.

**Comment by violetakochoska** [comment]
@N4M3Z here are the steps:

search user with his username
click on "look up organization"
after this, click on the "user/invite/address' button

The buttons became unclickable
Video: http://recordit.co/gs1ioMfZad

**Comment by N4M3Z** [comment]
Not relevant to the refactored version
