### ISSUE TITLE
Addresses are searched only by the "To" field

### ISSUE THREAD

**Issue by violetakochoska** [ProtonMail/Admin#29]
We often receive reports about users who cannot delete their custom domain address since they are seeing an error that messages associated with this address exist. When they are searching for this kind of messages, they cannot find them.

Here is one report:
Description: Hi! I've tried removing Email-addresses before without much success and I just tried it again. I have used the "Select All" feature after searching for "to:ovh@luca-kiebel.de" (which is the address I'm trying to remove), moved them to the trash and then deleted the trash (I also did the same with emails sent from that address), but still it says that I can't remove the address with messages associated with it... 
Username: ivara 
Contact Email: ivara@protonmail.com

Sure, this is what I see when I search for that address: 
http://i.imgur.com/Vh9NP6b.jpg

Luca Kiebel

**Comment by EpokK** [comment]
Wrong project
