### ISSUE TITLE
Username lookup done twice for the same username shows two pages

### ISSUE THREAD

**Issue by mojsomk** [ProtonMail/Admin#32]
1. Enter username 
2. Press enter
3. Click on User/Address/Invite

The same account is shown twice in a row.

**Comment by N4M3Z** [comment]
I can't reproduce on Chrome or Safari on OS X with the latest Admin panel version 0.11. Please post a screenshare if the issue persists.

**Comment by mojsomk** [comment]
It`s nothing critical.
http://recordit.co/sAAwbYfve9

**Comment by N4M3Z** [comment]
I can't reproduce it even on the old admin panel. Might be browser specific? Please confirm that this issue is gone in the admin panel.

**Comment by N4M3Z** [comment]
Not relevant to the refactored version
