### ISSUE TITLE
The left panel is not showing the options occasionally

### ISSUE THREAD

**Issue by violetakochoska** [ProtonMail/Admin#34]
This is hard to reproduce. I know that it's happening mostly when I am checking sent messages from users. 
For example I am checking some user on abuse and I am not seeing the side options anymore.

I need to refresh the browser in orde to see the left panel options.

![screen shot 2016-12-31 at 09 23 13 am](https://cloud.githubusercontent.com/assets/13854518/21675837/92cbdc1c-d333-11e6-8bbf-1986675d0ce1.png)
![screen shot 2016-12-31 at 09 23 03 am](https://cloud.githubusercontent.com/assets/13854518/21675853/9b744fd4-d333-11e6-9065-5c9257a8094c.png)

**Comment by N4M3Z** [comment]
Not relevant to the refactored version
